# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ac6d90bedcae406d319ac24188ab5965"
name = "gohighlevel-integration"
application_url = "http://localhost/new-install"
embedded = false

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_orders,read_products,write_draft_orders,write_customers"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "http://localhost" ]
